## Numpy Assignment
Student Name: AINOMUGISHA KING JOSSSY

## Instructions:
- Please complete the questions below.
- for each cell, complete it with good essays and code examples
- Please comment your code indicating how you approached the problem

# What is NumPy, and what are some of its key features?


#NumPy (Numerical Python)
- is a fundamental, open-source Python library for scientific computing used primarily for numerical computing.
##Key Features of NumPy
- N-Dimensional Arrays (ndarray):
At its core, NumPy introduces the ndarray object, a powerful and efficient data structure for representing homogeneous, multi-dimensional arrays. Unlike Python lists, ndarray elements must all be of the same data type, enabling optimized memory usage and faster computations.
- Vectorized Operations and Universal Functions (ufuncs):
NumPy allows for element-wise operations on entire arrays without the need for explicit Python loops. These "vectorized" operations, often implemented as highly optimized C code, significantly enhance performance for mathematical and logical operations. Universal functions (ufuncs) are a key component of this, providing efficient element-wise operations like sin, cos, and exp.
- Broadcasting:
This powerful feature allows NumPy to perform operations on arrays of different shapes and sizes by automatically aligning their dimensions. This eliminates the need for manual reshaping or explicit loops when combining arrays of varying configurations, simplifying code and improving efficiency.
- Indexing and Slicing:
NumPy provides robust and flexible indexing and slicing capabilities, allowing users to easily access and manipulate subsets of data within arrays. This includes advanced techniques like boolean indexing and fancy indexing for selecting elements based on conditions or specific indices.
- Linear Algebra Capabilities:
NumPy includes a comprehensive linear algebra library, providing functions for common operations such as matrix multiplication, determinants, eigenvalues, and decompositions, essential for various scientific and machine learning applications.
- Random Number Generation:
NumPy offers a robust module for generating various types of random numbers and distributions, crucial for simulations, statistical analysis, and machine learning algorithms.
- Performance Optimization:
NumPy is optimized for performance, with many of its core routines implemented in C or C++, allowing it to handle large datasets and perform computations significantly faster than pure Python code.
- Integration with Other Libraries:
NumPy serves as the foundation for many other scientific computing libraries in Python, including SciPy (for scientific and technical computing), Pandas (for data analysis), and scikit-learn (for machine learning), enabling seamless data flow and analysis across different tools.

In [2]:
import numpy as np

# Create a 2D array
a = np.array([[1, 2], [3, 4]])

# Add 10 to every element
b = a + 10

# Multiply matrices
c = np.dot(a, b.T)

print(c)

[[35 41]
 [81 95]]


In [1]:
# to install numpy when you have python installed.

#conda install numpy or

#pip install numpy

# How do you create a NumPy array using Python's built-in range() function?


In [3]:
import numpy as np  # Import the NumPy library

# Create a NumPy array using Python's range() from 0 to 4
arr = np.array(range(5))

# Print the resulting array
print(arr)


[0 1 2 3 4]


# What is the difference between a scalar value and a vector in NumPy?
with code example

#Scalar
A single value (0-dimensional array).

- Has no axes or shape.

- Think of it like a single number: 5, 3.14, etc.

#Vector
- A 1-dimensional array (a list of values).

- Has a shape like (n,) — e.g., (3,) for 3 elements.



In [4]:
import numpy as np

# Scalar value
scalar = np.array(7)
print("Scalar:", scalar)
print("Scalar shape:", scalar.shape)
print("Scalar ndim:", scalar.ndim)

print()

# Vector (1D array)
vector = np.array([1, 2, 3])
print("Vector:", vector)
print("Vector shape:", vector.shape)
print("Vector ndim:", vector.ndim)


Scalar: 7
Scalar shape: ()
Scalar ndim: 0

Vector: [1 2 3]
Vector shape: (3,)
Vector ndim: 1


# How do you calculate the mean of a NumPy array using the mean() function?

Examples



In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean_value = np.mean(arr)  # OR arr.mean()
print("Mean:", mean_value)


Mean: 30.0


# What is broadcasting in NumPy, and how can it be useful?


##Broadcasting
is a powerful feature in NumPy that allows arrays of different shapes and sizes to be used together in arithmetic operations without explicitly resizing them.
##How it can be  Useful
- Simplifies code (no need for explicit loops)

- Faster computation (vectorized operations)

- Memory-efficient (no extra memory copies needed

# How can you slice a NumPy array to extract a subarray?




- In NumPy, you can slice arrays similarly to Python lists using colons (:) to specify ranges of indices. Slicing lets you extract subarrays from 1D, 2D, or higher-dimensional arrays.
"array[start:stop:step]"


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

subarr = arr[1:4]  # Extract elements at index 1, 2, and 3
print(subarr)


[20 30 40]


# What are some of the available functions for performing element-wise operations on NumPy arrays?


## 1 Arithmetic Operations
These are basic math operations.

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Now element-wise operations will work:
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)


a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]


##2. Mathematical Functions
NumPy has built-in math functions that apply to each element:

In [5]:
np.sqrt(a)    # Square root
np.exp(a)     # e^a (exponential)
np.log(a)     # Natural log
np.abs(a)     # Absolute value

a = np.array([1, 4, 9])
print(np.sqrt(a))  # [1. 2. 3.]


[1. 2. 3.]


##3. Trigonometric Functions
Apply trigonometry to each number (in radians):

In [6]:
np.sin(a)
np.cos(a)
np.tan(a)

a = np.array([0, np.pi/2])
print(np.sin(a))  # [0. 1.]


[0. 1.]


##4. Comparison Functions
You can compare each element to a value or another array:

In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print("a > 2:", a > 2)          # [False False  True]
print("a == b:", a == b)        # [False  True False]
print("greater:", np.greater(a, b))  # [False False  True]


a > 2: [False False  True]
a == b: [False  True False]
greater: [False False  True]


##5. Logical Operations
Use logical conditions with arrays:
"np.logical_and(a > 0, a < 3)"


In [9]:
a = np.array([0, 1, 2, 3])
print(np.logical_and(a > 0, a < 3))  # [False  True  True False]


[False  True  True False]


##6 Rounding Functions

In [10]:
np.round(a)
np.floor(a)
np.ceil(a)

a = np.array([1.4, 2.6])
print(np.round(a))  # [1. 3.]


[1. 3.]


# How do you reshape a NumPy array to have a different shape?





##Reshaping a NumPy Array
In NumPy, you can use the .reshape() method to change the shape of an array without changing its data.
- syntax"new_array = array.reshape(new_shape)
"
- new_shape: A tuple specifying the new dimensions, like (rows, columns)

- The total number of elements must stay the same before and after reshaping.

In [11]:
##Reshape 1D to 2D
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2 rows and 3 columns
b = a.reshape(2, 3)

print("Original array:", a)
print("Reshaped array:\n", b)/##

"""
 ##Reshape 2D to 1D
 b = np.array([[1, 2, 3],
              [4, 5, 6]])

# Flatten to 1D
flat = b.reshape(-1)
print(flat)  # Output: [1 2 3 4 5 6



Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


# How do you perform matrix multiplication on two NumPy arrays using the dot() function?


In [12]:
import numpy as np

# Example matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using dot()
C = np.dot(A, B)

print(C)


[[19 22]
 [43 50]]


# How can you use the where() function to apply a condition to a NumPy array?


In [14]:
## syntax "np.where(condition, value_if_true, value_if_false)""
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Replace values greater than 30 with 1, others with 0
result = np.where(arr > 30, 1, 0)

print(result)


[0 0 0 1 1]


# What is the difference between the flatten() and ravel() functions in NumPy?




# 1. flatten()
- Returns a copy of the original array.

- Changes to the result do not affect the original array.

- Slightly slower due to copying

In [15]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = a.flatten()

b[0] = 100
print("Original:\n", a)
print("Flattened (copy):", b)


Original:
 [[1 2]
 [3 4]]
Flattened (copy): [100   2   3   4]


##2. ravel()
- Returns a view (if possible) of the original array.

- Changes to the result may affect the original array.

- Faster and uses less memory.

In [16]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()

b[0] = 100
print("Original:\n", a)
print("Raveled (view):", b)


Original:
 [[100   2]
 [  3   4]]
Raveled (view): [100   2   3   4]


# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?


##1. Integer array indexing
You can pass arrays or lists of indices to select specific elements by their positions.

In [17]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Select elements at indices 1, 3, and 4
indices = [1, 3, 4]
selected = arr[indices]

print(selected)  # Output: [20 40 50]


[20 40 50]


##2. Boolean indexing
Use a boolean mask array of the same shape to pick elements where the mask is True:

In [18]:

arr = np.array([10, 15, 20, 25, 30])

mask = arr > 20
selected = arr[mask]

print(selected)  # Output: [25 30]


[25 30]


# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

#How broadcasting works:
NumPy compares the shapes of the two arrays starting from the trailing (rightmost) dimensions and works left:

Dimensions are compatible when they are equal, or one of them is 1.

- If compatible, NumPy “broadcasts” (repeats) the array along the dimension with size 1 to match the other.

- If not compatible, it raises an error.

In [26]:
# Scalar with array
import numpy as np

a = np.array([1, 2, 3])
b = 5  # scalar

print(a + b)  # Adds 5 to each element: [6 7 8]
"""
#Different shapes, but compatible
a = np.array([[1, 2, 3],
              [4, 5, 6]])  # shape (2,3)

b = np.array([10, 20, 30])  # shape (3,)

print(a + b)
#Adding a column vector to a matrix
a = np.array([[1, 2, 3],
              [4, 5, 6]])  # shape (2,3)

b = np.array([[10],
              [20]])       # shape (2,1)

print(a + b)
"""




[6 7 8]


'\n#Different shapes, but compatible\na = np.array([[1, 2, 3],\n              [4, 5, 6]])  # shape (2,3)\n\nb = np.array([10, 20, 30])  # shape (3,)\n\nprint(a + b)\n#Adding a column vector to a matrix\na = np.array([[1, 2, 3],\n              [4, 5, 6]])  # shape (2,3)\n\nb = np.array([[10],\n              [20]])       # shape (2,1)\n\nprint(a + b)\n'

### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [27]:
import numpy as np

def main():
    # Prompt user to enter numbers separated by commas
    user_input = input("Enter a list of numbers separated by commas: ")

    # Convert input string to list of floats
    try:
        numbers_list = [float(num.strip()) for num in user_input.split(',')]
    except ValueError:
        print("Error: Please enter valid numbers separated by commas.")
        return

    # Convert list to 1D NumPy array
    arr = np.array(numbers_list)

    # Calculate statistics using NumPy functions
    mean = np.mean(arr)
    median = np.median(arr)
    std_dev = np.std(arr)
    maximum = np.max(arr)
    minimum = np.min(arr)

    # Display the results
    print("\nStatistics for the input array:")
    print(f"Mean: {mean}")
    print(f"Median: {median}")
    print(f"Standard Deviation: {std_dev}")
    print(f"Maximum: {maximum}")
    print(f"Minimum: {minimum}")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by commas: 1,2

Statistics for the input array:
Mean: 1.5
Median: 1.5
Standard Deviation: 0.5
Maximum: 2.0
Minimum: 1.0
